[package]
name = "rusty-playerctl-presence"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
discord-sdk = "0.3.7"
mpris = "2.0.1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
